### ISSUE TITLE
stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by LazyZhu** [nhoizey/jekyll-postfiles#2]
C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/cleaner.rb:73:in `parent_dirs': stack level too deep (SystemStackError)
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/cleaner.rb:77:in `parent_dirs'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/cleaner.rb:77:in `parent_dirs'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/cleaner.rb:77:in `parent_dirs'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/cleaner.rb:77:in `parent_dirs'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/cleaner.rb:77:in `parent_dirs'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/cleaner.rb:77:in `parent_dirs'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/cleaner.rb:77:in `parent_dirs'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/cleaner.rb:77:in `parent_dirs'
         ... 9350 levels...
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/exe/jekyll:13:in `<top (required)>'
        from C:/tools/ruby23/bin/jekyll:23:in `load'
        from C:/tools/ruby23/bin/jekyll:23:in `<main>'

**Comment by SummerBuger** [comment]
are you fixed this problem? I can not fix this with the similar issue. @LazyZhu

**Comment by nhoizey** [comment]
I don't know how to fix this.

Did you try with a newer version of Jekyll?

**Comment by mohkale** [comment]
I don't think this is an issue with this plugin and I don't think it's still active anyways. This issue should be  closed.
